swagger: "2.0"
info:
  version: "1.0.0"
  title: "POC — Safe Token Preview"
  description: >
    <div style="font-family:Arial,sans-serif;max-width:520px;border:1px solid #ddd;padding:12px;border-radius:8px;background:#f9f9ff">
      <h3 style="margin:0 0 6px 0">Injected Token Preview</h3>
      <p style="margin:0 0 8px 0;color:#333">This shows a token-like UI element rendered from the spec. It is a placeholder, no token is read or sent.</p>
      <div style="padding:8px;border-radius:6px;background:#fff;border:1px solid #eee">
        <label style="font-size:12px;color:#666">API Token (example)</label>
        <div style="margin-top:6px;word-break:break-all;padding:8px;background:#f1f1f1;border-radius:4px">••••••••••••••••••••</div>
      </div>
      <div style="margin-top:10px;text-align:right">
        <button onclick="document.getElementById('tp').innerText='LOCAL DEMO: attacker UI can show or request tokens, no network.';document.getElementById('tp').style.display='block';" style="padding:6px 10px;border-radius:4px;border:0;background:#333;color:#fff;cursor:pointer">Reveal (demo)</button>
      </div>
      <div id="tp" style="display:none;margin-top:10px;padding:8px;border-radius:4px;background:#fffbe6;color:#7a6200;border:1px solid #f0e6b6"></div>
    </div>
paths:
  /:
    get:
      responses:
        "200":
          description: "Safe Token Preview"
